/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f407xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    // Setting Port D to turn on a LED

    RCC		->	AHB1ENR	|=	RCC_AHB1ENR_GPIODEN;		//	Setting RCC_AHB1 bus port D
    GPIOD	->	MODER	|=	GPIO_MODER_MODE12_0;		//	Setting GPIO port D mode
    GPIOD	->	ODR		|=	GPIO_ODR_OD12;		//	Setting GPIO port D output data

	/* Loop forever */
	for(;;);
}
