/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t	*p_RCC_ena		=	(uint32_t*)	0x40023830;		// Pointer pointing to the the address of the Reset and clock control enable for GPIO PORT C and PORT D(LEDS)
	uint32_t	*p_GPIOCMODE	=	(uint32_t*)	0x40020800;		// Pointer pointing to the address of the GPIO port C configuration mode
	uint32_t 	*p_GPIODMODE	=	(uint32_t*)	0x40020C00;		// Pointer pointing to the address of the GPIO port D configuration mode
	uint32_t 	*p_GPIOCOUTC	=	(uint32_t*)	0x40020814;		// Pointer pointing to the address to active the PIN 14 of the port C
	uint32_t 	*p_GPIODOUTC	=	(uint32_t*)	0x40020C14;		// Pointer pointing to the address to active the PIN 14 of the port D

	// Setting PIN 14 of the port D

	*p_RCC_ena		|=	0x08;			// We activate the enable for the port D
	*p_GPIODMODE	&=	0xCFFFFFFF;		// We clean all register for port D mode
	*p_GPIODMODE 	|=	0x10000000;		// We designate Pin 14 as an output of the port D
	*p_GPIODOUTC 	|=	0x4000;			// We send a 1 to the output of the PIN 14 of the port D

	// Setting PIN 14 of the Port C

	*p_RCC_ena		|=	0x04;			// We activate the enable for the port C
	*p_GPIOCMODE	&=	0xCFFFFFFF;		// We clean all register for port C mode
	*p_GPIOCMODE	|=	0x10000000;		// We designate Pin 14 as an output of the port C
	*p_GPIOCOUTC	|=	0x4000;		// We send a 1 to the output of the PIN 14 of the port C

	/* Loop forever */
	for(;;);
}
