/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "MYLIBRARY.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// Defining my pointers
	
	RCC_AHB1ENR_t 	volatile *const p_RCCENR 	= (RCC_AHB1ENR_t*) RCC_AHB1ENR; 	// Pointer saving the direction of the registers of my RCC_AHB1 bus
	GPIOs_MODER_t 	volatile *const p_GPIODMODE = (GPIOs_MODER_t*) GPIOs_MODER;		// Pointer saving the direction of the registers of the GPIOs mode configuration
	GPIOs_ODR_t	 	volatile *const p_GPIODOUTC = (GPIOs_ODR_t*)   GPIOs_ODR;	// Pointer saving the direction of the registers of the  GPIOs out data configuration

	
	// Setting PORT D registers
	
	p_RCCENR 	->	GPIODEN = GPIOD_ON;		// Setting the RCC of GPIO port D
	p_GPIODMODE -> 	MODER12 = OUTPUT_MODE;			// Setting the GPIO mode of moder #12 of the port D
	p_GPIODOUTC -> 	pin_12 	= TURNING_ON;			// Setting the output data of the pin 12 of the port D 

    /* Loop forever */
	for(;;);
}
