/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "MYLIBRARY.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC_AHB1ENR_t 	volatile *const p_RCCENR 	= (RCC_AHB1ENR_t*) RCC_AHB1ENR;
	GPIOs_MODER_t 	volatile *const p_GPIODMODE = (GPIOs_MODER_t*) GPIOs_MODER;
	GPIOs_ODR_t	 	volatile *const p_GPIODOUTC = (GPIOs_ODR_t*)   GPIOs_ODR;

	p_RCCENR 	->	GPIODEN = GPIOD_ON;
	p_GPIODMODE -> 	MODER12 = OUTPUT_MODE;
	p_GPIODOUTC -> 	pin_12 	= TURNING_ON;







    /* Loop forever */
	for(;;);
}
